### ISSUE TITLE
improve regex - upper-case fails

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/fallback-wolfram-alpha#12]
question parser needs some work

```
02:57:44.023 - WolframAlphaSkill - DEBUG - WolframAlpha fallback attempt: When will the world end?
02:57:44.024 - WolframAlphaSkill - DEBUG - Non-question, ignoring: When will the world end?

02:52:10.739 - WolframAlphaSkill - DEBUG - WolframAlpha fallback attempt: What is the speed of light?
02:52:10.739 - WolframAlphaSkill - DEBUG - Non-question, ignoring: What is the speed of light?
``` 
this is when i type in the cli, if i do it lower case it works

`02:57:56.123 - WolframAlphaSkill - DEBUG - WolframAlpha fallback attempt: when will the world end
02:57:56.123 - WolframAlphaSkill - DEBUG - Querying WolframAlpha: when will the world end`

**Comment by krisgesling** [comment]
This seems to have been fixed by Steve earlier this year
https://github.com/MycroftAI/fallback-wolfram-alpha/commit/cd96812983c4be415eea0110e5c81f34fb317572

Closing
