### ISSUE TITLE
No change in Mycroft after installing

### ISSUE THREAD

**Issue by benblur4** [MycroftAI/fallback-wolfram-alpha#2]
Mycroft still doesn't know the speed of light or 2 + 2 even after install.

**Comment by TodaysITSolutions** [comment]
Looks to still be broken.

**Comment by MatthewScholefield** [comment]
This is because of issues with the app ID in the backend. Because of this, a developer key has to be entered on the Web UI

**Comment by penrods** [comment]
As of this afternoon we have the default API back online!  This should be working for you again, no developer key  necessary.

**Comment by penrods** [comment]
I'm going to go ahead and consider this one solved and close it.  Let me know if you are still having issues.

**Comment by benblur4** [comment]
Thanks man! I'll check it out.
