### ISSUE TITLE
issue with MSM update?

### ISSUE THREAD

**Issue by valdr** [MycroftAI/fallback-wolfram-alpha#20]
When I run `msm update`, I get the following error for this skill:

`"ERROR - Error running update_skill on fallback-wolfram-alpha: GitException(Git command failed: GitCommandError(['git', 'fetch'], 255, b'error: cannot open .git/FETCH_HEAD: Permission denied\n', b''))"`

Anything I am doing wrong?

**Comment by KathyReid** [comment]
https://mycroft.ai/documentation/msm/#git-command-error-failed-to-update-repo

Let us know how you go :-)

**Comment by valdr** [comment]
Thanks for troubleshooting with me in the chat, Kathy.
It was the permissions here too.

Closing the issue.
