### ISSUE TITLE
Mycroft turns hyphens into unknown characters

### ISSUE THREAD

**Issue by davbl** [MycroftAI/fallback-wolfram-alpha#33]
![image](https://user-images.githubusercontent.com/11878478/60284465-75dbe980-98c0-11e9-95f2-3ae43e085c6b.png)

**Comment by penrods** [comment]
My guess is that those are unicode dashes (e.g. an n-dash or m-dash instead of a simple hypen), which the CLI can't draw and represents with a box.

**Comment by forslund** [comment]
In my terminal the characters for this query is rendered correctly so it's to do with the terminal / ssh client rather than with mycroft.

**Comment by forslund** [comment]
Closing the issue for now.
