### ISSUE TITLE
Data not available

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/fallback-wolfram-alpha#5]
`Where do I find a tall building?`
`>> Data not available`

**Comment by penrods** [comment]
http://www.wolframalpha.com/input/?i=where+do+I+find+a+tall+building

Yep, we should catch this

**Comment by krisgesling** [comment]
WolframAlpha is now returning a result of `(data not available)` for this query along with the location of a 1925 artwork named "tall building".

Other similar questions like "where do I find the eiffel tower" or "where do I find green meadow" respond properly.

So I'm assuming this is resolved. Feel free to re-open if you disagree.
